---

- src: geerlingguy.docker
  version: 6.0.3

- src: git+https://github.com/devture/com.devture.ansible.role.docker_sdk_for_python.git
  version: 6ba3be490b6f4c6f35ea109aeb8e533fa231b3a5

- src: git+https://github.com/devture/com.devture.ansible.role.playbook_help.git
  version: c1f40e82b4d6b072b6f0e885239322bdaaaf554f

- src: git+https://github.com/devture/com.devture.ansible.role.systemd_docker_base.git
  version: 327d2e17f5189ac2480d6012f58cf64a2b46efba

- src: git+https://github.com/devture/com.devture.ansible.role.timesync.git
  version: 660f384f176a9ea3b5cc702bde39e7dc10bf6186

- src: git+https://github.com/devture/com.devture.ansible.role.playbook_state_preserver.git
  version: ff2fd42e1c1a9e28e3312bbd725395f9c2fc7f16

- src: git+https://github.com/devture/com.devture.ansible.role.postgres.git
  version: b547c81ed69a659be22016df35cc0d82cb444a76

- src: git+https://github.com/devture/com.devture.ansible.role.traefik.git
  version: 0b1c06cbeb730425cdc1a251df5212ddd8cad8e0

- src: git+https://github.com/devture/com.devture.ansible.role.systemd_service_manager.git
  version: 6ccb88ac5fc27e1e70afcd48278ade4b564a9096

- src: git+https://github.com/devture/com.devture.ansible.role.playbook_runtime_messages.git
  version: 9b4b088c62b528b73a9a7c93d3109b091dd42ec6
