---

- src: geerlingguy.docker
  version: 6.1.0

- src: git+https://github.com/devture/com.devture.ansible.role.docker_sdk_for_python.git
  version: 129c8590e106b83e6f4c259649a613c6279e937a

- src: git+https://github.com/devture/com.devture.ansible.role.playbook_help.git
  version: c1f40e82b4d6b072b6f0e885239322bdaaaf554f

- src: git+https://github.com/devture/com.devture.ansible.role.systemd_docker_base.git
  version: 327d2e17f5189ac2480d6012f58cf64a2b46efba

- src: git+https://github.com/devture/com.devture.ansible.role.timesync.git
  version: 3d5bb2976815958cdce3f368fa34fb51554f899b

- src: git+https://github.com/devture/com.devture.ansible.role.playbook_state_preserver.git
  version: ff2fd42e1c1a9e28e3312bbd725395f9c2fc7f16

- src: git+https://github.com/devture/com.devture.ansible.role.postgres.git
  version: a1bb78d194434b38005f3a9e623bfa4b2c06c7bc

- src: git+https://github.com/devture/com.devture.ansible.role.postgres_backup.git
  version: 8e9ec48a09284c84704d7a2dce17da35f181574d

- src: git+https://github.com/devture/com.devture.ansible.role.woodpecker_ci_server.git
  version: 85a1258f37c614ea7cba8d946206475a2c48b06b

- src: git+https://github.com/devture/com.devture.ansible.role.woodpecker_ci_agent.git
  version: 07f679feb928932cebd61434c83265c9de653214

- src: git+https://github.com/devture/com.devture.ansible.role.container_socket_proxy.git
  version: v0.1.1-1

- src: git+https://github.com/devture/com.devture.ansible.role.traefik.git
  version: v2.9.8-1

- src: git+https://github.com/devture/com.devture.ansible.role.systemd_service_manager.git
  version: 6ccb88ac5fc27e1e70afcd48278ade4b564a9096

- src: git+https://github.com/devture/com.devture.ansible.role.playbook_runtime_messages.git
  version: 9b4b088c62b528b73a9a7c93d3109b091dd42ec6
