---

gitea_backup_enabled: true

gitea_backup_base_path: "{{ gitea_base_path }}/backup"
gitea_backup_bin_path: "{{ gitea_backup_base_path }}/bin"
gitea_backup_etc_path: "{{ gitea_backup_base_path }}/etc"
gitea_backup_data_path: "{{ gitea_backup_base_path }}/data"

# gitea_backup_encryption_password holds a password to use for symmetric gpg encryption
gitea_backup_encryption_password: ''

# gitea_backup_stop_gitea_while_running controls whether the Gitea systemd service will be stopped while backups are running.
# It will be started back up after the backup process.
#
# By default, we favor extra safety, at the expense of some downtime while backing up.
gitea_backup_stop_gitea_while_running: true

# gitea_backup_paths_to_backup contains a list of paths to include in the backup.
# Example: [/gitea]
gitea_backup_paths_to_backup: []

# gitea_backup_paths_to_exclude contains a list of paths to exclude from the backup
# Example: [/gitea/something, /gitea/postgres/data]
#
# Playbook-managed paths are injected into `gitea_backup_paths_to_exclude_auto`.
# To define your own paths, use `gitea_backup_paths_to_exclude_additional`.
# If you'd like to override the auto-excluded paths from the playbook, override `gitea_backup_paths_to_exclude_auto`
# or change `gitea_backup_paths_to_exclude`.
gitea_backup_paths_to_exclude: "{{ gitea_backup_paths_to_exclude_auto + gitea_backup_paths_to_exclude_additional }}"
gitea_backup_paths_to_exclude_auto: [gitea_backup_data_path + '/gitea-latest-backup.tar.gpg']
gitea_backup_paths_to_exclude_additional: []

# gitea_backup_schedule contains a systemd OnCalendar definition which controls how often `gitea-backup.timer` runs
gitea_backup_schedule: '*-*-* 06:30:00'

gitea_backup_b2_enabled: false
gitea_backup_b2_container_image: docker.io/tianon/backblaze-b2:3.6.0
gitea_backup_b2_container_image_force_pull: "{{ gitea_backup_b2_container_image.endswith(':latest') }}"
gitea_backup_b2_bucket: bucket-name
gitea_backup_b2_key_id: ~
gitea_backup_b2_key_secret: ~

# gitea_backup_post_backup_custom_shell_commands contains a multiline string containing shell (bash) commands to execute
# after the backup file is created and before pushing it to any backup providers.
#
# These commands are injected into `../templates/backup.j2` (`{{ gitea_backup_bin_path }}/backup` on the server).
#
# Also see: gitea_backup_before_exit_custom_shell_commands
#
# Example:
#
# # The commands below expose the latest backup as a `/home/backup/gitea-latest-backup.tar.gpg` file,
# # to be periodically pulled from a remote machine over SSH (via `backup@gitea.DOMAIN`).
# # Setting up this `backup` user, home directory and access (SSH keys, etc.) is not managed by the playbook.
# gitea_backup_post_backup_custom_shell_commands: |-
#   cp {{ gitea_backup_data_path }}/gitea-latest-backup.tar.gpg /home/backup/gitea-latest-backup.tar.gpg
#   chown backup:backup /home/backup/gitea-latest-backup.tar.gpg
#   chmod 400 /home/backup/gitea-latest-backup.tar.gpg
gitea_backup_post_backup_custom_shell_commands: ''

# gitea_backup_before_exit_custom_shell_commands contains a multiline string containing shell (bash) commands to execute
# at the end of the backup script.
#
# These commands are injected into `../templates/backup.j2` (`{{ gitea_backup_bin_path }}/backup` on the server).
#
# Example:
#
# # The command below signals to a https://healthchecks.io/ check that the backup script
# # reached the end without hitting any errors.
# gitea_backup_before_exit_custom_shell_commands: |-
#   curl -m 10 --retry 5 https://healthchecks.DOMAIN/ping/healthcheck-id
gitea_backup_before_exit_custom_shell_commands: ''
