---

- name: Ensure systemd reloaded
  ansible.builtin.service:
    daemon_reload: true

- name: Ensure Gitea services stopped
  ansible.builtin.service:
    name: "{{ item.name }}"
    state: stopped
  with_items: "{{ gitea_services_list | sort (attribute='priority', reverse=true) }}"

- name: Ensure Gitea services started
  ansible.builtin.service:
    name: "{{ item.name }}"
    state: started
    enabled: "{{ gitea_services_autostart_enabled }}"
  with_items: "{{ gitea_services_list | sort (attribute='priority') }}"
