---

- name: Ensure Gitea services stopped
  ansible.builtin.service:
    name: "{{ item.name }}"
    state: stopped
  with_items: "{{ gitea_systemd_services_list | sort (attribute='priority', reverse=true) }}"
